# STA 6714 Final Project

Author: Robert Norberg

Due: April 23, 2014

Date Ran: `r format(Sys.Date(), '%B %d, %Y')`

----

```{r ChunkSettings, echo=FALSE, warning=FALSE, cache=FALSE, message=FALSE, results='hide'}
# Clear working environment
rm(list=ls())

# Options for document compilation
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, comment=NA, fig.height=8, fig.width=7, fig.cap='', results='hide')

# Set table options for neat tables
library(pander)
panderOptions('table.split.table', 120)
panderOptions('table.split.cells', 30)

# Globally set plot parameters
library(ggplot2)
theme_set(theme_bw(base_size=18))
theme_update(panel.grid.major=element_line(colour="#CCCCCC", size=0.3), panel.grid.minor=element_line(colour="grey96", size=0.7))

library(data.table)
```

```{r InfileData, cache=TRUE}
train <- fread('C:/Users/Robert/cloud/Classes/Data Prep/Final Project/Data/WANGphy_train.csv')
```

## Executive Summary (1 Page) 


## Data Preparation

### Exploration

```{r child='C:/Users/Robert/cloud/Classes/Data Prep/Final Project/DataExploration.Rmd'}
```

### Missing Values Indicators and MVP

```{r child='C:/Users/Robert/cloud/Classes/Data Prep/Final Project/MissingValuePattern.Rmd'}
```

### Missing Value Imputation 

```{r child='C:/Users/Robert/cloud/Classes/Data Prep/Final Project/MissingValueImputation.Rmd'}
```

### Transformations 

### Outliers 

## Model Building

## Model Performance 

### Model performance evaluation 

#### ROC curve

#### c statistics

#### Validation Sum Squares

### Variable Importance 

### Variable Impact to the Target Variable 

## Conclusions 

-----

## Appendices

### Tables

```{r, results='hide'}
zerotable <- fread('C:/Users/Robert/cloud/Classes/Data Prep/Final Project/Percent Zeros.csv')
zerotable <- zerotable[, x:=paste0(x, '%')]
zerotable <- zerotable[x=='NA%', x:='N/A']
setnames(zerotable, c('Variable', "% 0's"))
```

```{r, results='asis'}
pander(zerotable)
```

```{r}
misstable <- fread('C:/Users/Robert/cloud/Classes/Data Prep/Final Project/Percent Missing.csv')
setnames(misstable, c('Variable', '% Missing'))
```

```{r, results='asis'}
pander(misstable)
```



### Works Cited

```{r, results='asis'}
# Create bibliography to cite packages used
allLibs <- .packages()
library(knitcitations)
write.bib(allLibs, file="Appendix.bib")
read.bib("Appendix.bib")
```

-----

### R code

```{r all-code, ref.label=all_labels(), echo=TRUE, eval=FALSE, tidy.opts=list(keep.blank.line=T)}
```